import { Injectable } from "@angular/core";
import { Personnage } from "../models/Personnage";
import { GroupeMock } from "../models/groupeMock";

@Injectable({ providedIn:'root' })
export class MockGroupeService {

groupeList: GroupeMock[]=[
new GroupeMock( 1,"L’équipage du Chapeau de Paille", 11),
new GroupeMock( 2,"L’équipage du Roux", 0),
new GroupeMock( 3,"L’équipage d’Alvida", 0),
new GroupeMock( 4,"L’équipage du Clown", 0),
new GroupeMock( 5,"L’équipage des Pirates Roger", 24),
new GroupeMock( 6,"L’équipage du Capitaine Usopp", 0),
new GroupeMock( 7,"L’équipage du Chat Noir", 3),
new GroupeMock( 8,"L’armada Pirate de Don Krieg", 3),
new GroupeMock( 9,"L’équipage des Cuisiniers", 0),
new GroupeMock( 10,"L’équipage d’Arlong", 3),
new GroupeMock( 11,"L’équipage des Pirates Yes", 0),
new GroupeMock( 12,"L’équipage du Rumbar", 3),
new GroupeMock( 13,"L’équipage des Géants", 0),
new GroupeMock( 14,"L’équipage du Bliking", 0),
new GroupeMock( 15,"L’équipage des Tulipes", 0),
new GroupeMock( 16,"L’équipage de Barbe Blanche", 58),
new GroupeMock( 17,"Ligue des Primates", 3),
new GroupeMock( 18,"L’équipage de Hakahoka", 0),
new GroupeMock( 19,"l’équipage du New Age", 0),
new GroupeMock( 20,"L’équipage de Roshio", 0),
new GroupeMock( 21,"L’équipage de Don Quichotte", 15),
new GroupeMock( 22,"L’équipage de Barbe Noire", 12),
new GroupeMock( 23,"L’équipage des Fanged Toad", 0),
new GroupeMock( 24,"L’équipage de Foxy", 3),
new GroupeMock( 25,"L’équipage des Gros Casques", 0),
new GroupeMock( 26,"L’équipage des Pirates du Soleil", 3),
new GroupeMock( 27,"Pirate de l’Espace", 0),
new GroupeMock( 28,"Thriller Bark", 4),
new GroupeMock( 29,"L’équipage du Rolling", 1),
new GroupeMock( 30,"L’équipage des Marquereaux", 0),
new GroupeMock( 31,"L’équipage des Candys", 0),
new GroupeMock( 32,"L’équipage du Hearth", 5),
new GroupeMock( 33,"L’équipage de Kid", 4),
new GroupeMock( 34,"L’équipage de Hawkins", 0),
new GroupeMock( 35,"L’équipage de Drake", 0),
new GroupeMock( 36,"L’équipage du On-Air", 0),
new GroupeMock( 37,"L’équipage de Bonney", 0),
new GroupeMock( 38,"L’équipage du Fire Tank", 6),
new GroupeMock( 39,"L’équipage des Moines Dépravés", 1),
new GroupeMock( 40,"L’équipage des Acumates", 0),
new GroupeMock( 41,"L’équipage des Pirates Kuja", 4),
new GroupeMock( 42,"L’équipage des Spade", 0),
new GroupeMock( 43,"L’équipage de Barbe Brune", 1),
new GroupeMock( 44,"L’équipage aux Cent Bêtes", 60),
new GroupeMock( 45,"L’équipage du Lion d’Or", 5),
new GroupeMock( 46,"L’équipage du Bluejam", 2),
new GroupeMock( 47,"L’équipage ASL", 0),
new GroupeMock( 48,"Faux Equipage du Chapeau de Paille", 8),
new GroupeMock( 49,"L’équipage de Caribou", 2),
new GroupeMock( 50,"L’équipage des Nouveaux Hommes-Poissons", 6),
new GroupeMock( 51,"L’équipage des Pirates Volants", 1),
new GroupeMock( 52,"L’équipage de Gyro", 0),
new GroupeMock( 53,"L’équipage de Big Mom", 91),
new GroupeMock( 54,"L’équipage d’Expédition", 0),
new GroupeMock( 55,"L’équipage des Magnifiques Pirates", 0),
new GroupeMock( 56,"L’équipage de Bartolomeo", 0),
new GroupeMock( 57,"Flotte Yonta Maria", 1),
new GroupeMock( 58,"L’équipage du Croissant de Lune", 0),
new GroupeMock( 59,"L’équipage de Diez Barrels", 0),
new GroupeMock( 60,"XXX Gym Martial Arts Alliances", 0),
new GroupeMock( 61,"Nouvel Equipage des Géants", 0),
new GroupeMock( 62,"L’équipage de Rocks", 1),
new GroupeMock( 63,"l’équipage de Ganzack", 0),
new GroupeMock( 64,"L’équipage Amigo", 0),
new GroupeMock( 65,"L’équipage du Phoenix", 0),
new GroupeMock( 66,"L’équipage de Bayan", 0),
new GroupeMock( 67,"L’équipage des Pirates Schneider", 2),
new GroupeMock( 68,"L’équipage de Wetton", 0),
new GroupeMock( 69,"Les Pirates à la citrouille", 0),
new GroupeMock( 70,"L’équipage des Flèches Rouges", 0),
new GroupeMock( 71,"L’équipage des Pirates à la Moustache", 0),
new GroupeMock( 72,"L’équipage des Pirates Trump", 5),
new GroupeMock( 73,"L’équipage de Gasparde", 5),
new GroupeMock( 74,"L’équipage de Zenny", 0),
new GroupeMock( 75,"L’équipage des Pirates du Sables", 0),
new GroupeMock( 76,"L’équipage Tearoom", 0),
new GroupeMock( 77,"L’équipage des Pirates Treasure", 0),
new GroupeMock( 78,"Baroque Works", 0),
new GroupeMock( 79,"Royaume de Luvneel", 0),
new GroupeMock( 80,"La Flotte de Happou", 0),
new GroupeMock( 81,"L'Équipage des Maquereaux", 1),
new GroupeMock( 82,"Marine", 50),
new GroupeMock( 83,"Dragon Célestes", 6),
new GroupeMock( 84,"Bigaro", 0),
new GroupeMock( 85,"L'Équipage de Mad Treasure", 0),
new GroupeMock( 86,"Royaume de Tontatta", 0),
new GroupeMock( 87,"Armarda du Chapeau de Paille", 20),
new GroupeMock( 88,"Baggy's Delivery", 5),
new GroupeMock( 89,"Buggy's Delivery", 6),
new GroupeMock( 90,"Cipher Pol", 10),
new GroupeMock( 91,"Enies Lobby", 3),
new GroupeMock( 92,"Impel Down", 10),
new GroupeMock( 93,"Royaume de Goa", 10),
new GroupeMock( 94,"Village de Shimotsuki", 3),
new GroupeMock( 95,"Archipel des Argao", 2),
new GroupeMock( 96,"Île des animaux étranges", 2),
new GroupeMock( 97,"Archipel des Gecko", 6),
new GroupeMock( 98,"Baratie", 3),
new GroupeMock( 99,"Archipel Conomi", 7),
new GroupeMock( 100,"Loguetown", 1),
new GroupeMock( 101,"Royaume de Lvneel", 1),
new GroupeMock( 102,"Baterilla", 1),
new GroupeMock( 103,"Royaume maléfique de Black Drum", 3),
new GroupeMock( 104,"Ohara", 3),
new GroupeMock( 105,"Pays des fleurs", 2),
new GroupeMock( 106,"Reverse Mountain", 0),
new GroupeMock( 107,"Île aux cactus", 2),
new GroupeMock( 108,"Little Garden", 2),
new GroupeMock( 109,"Île de Drum", 5),
new GroupeMock( 110,"Alabasta", 16),
new GroupeMock( 111,"Long Ring Long Land", 2),
new GroupeMock( 112,"Source de l'insouciance", 1),
new GroupeMock( 113,"Water Seven", 12),
new GroupeMock( 114,"Archipel des Sabaody", 4),
new GroupeMock( 115,"Archipel de Boing", 1),
new GroupeMock( 116,"Erbaf", 5),
new GroupeMock( 117,"Pays des Wa", 33),
new GroupeMock( 118,"Punk Hazard", 4),
new GroupeMock( 119,"Dressrosa", 7),
new GroupeMock( 120,"Green Bit", 2),
new GroupeMock( 121,"Zo", 10),
new GroupeMock( 122,"Royaume de Prodence", 2),
new GroupeMock( 123,"Royaume de Mogalo", 2),
new GroupeMock( 124,"Royaume de Germa", 6),
new GroupeMock( 125,"Sphinx", 1),
new GroupeMock( 126,"Skypiea", 20),
new GroupeMock( 127,"Weatheria", 1),
new GroupeMock( 128,"Île des hommes-poissons", 15),
new GroupeMock( 129,"La lune", 1),
new GroupeMock( 130,"Armée Révolutionnaire", 12),
new GroupeMock( 131,"Anciens membres du Baroque Works", 8),
new GroupeMock( 132,"Anciens membres du Cipher Pol", 7),
new GroupeMock( 133,"Anciens membres de la Marine", 2),
new GroupeMock( 134,"Esclave", 1),
new GroupeMock( 135,"Frères Voleurs", 2),
new GroupeMock( 136,"IÎle de la couronne", 0),
new GroupeMock( 137,"Île d'Asuka", 7),
new GroupeMock( 138,"Pirate des flèches rouges", 2),
new GroupeMock( 139,"Pirate au foyer", 1),
new GroupeMock( 140,"Pirate Moustachus", 1),
new GroupeMock( 141,"Île de Mecha", 4),
new GroupeMock( 142,"Néo Marine", 3),
new GroupeMock( 143,"Gran Tesero", 5),
new GroupeMock( 144,"Elegia", 2),
new GroupeMock( 145,"World Economic Journal", 1),
new GroupeMock( 146,"Cap des Jumeaux", 2),
new GroupeMock( 147,"Equipage de Bellamy", 1),
new GroupeMock( 148,"Equipage de Pandaman", 0),
new GroupeMock( 149,"Equipage de Bigalo", 1),];

getGroupeList(): GroupeMock[]{
    return [...this.groupeList];
}

getGroupeById(groupeId: number): GroupeMock {
    const idNum = Number(groupeId);
    const foundGroupe = this.groupeList.find(Groupe => Groupe.id === idNum );
    if (!foundGroupe){
        throw new Error('Groupe non trouvé !');
    }
    return foundGroupe;
}

getGroupeByName(nom: String): GroupeMock {
    const foundGroupe = this.groupeList.find(Groupe => Groupe.nom === nom );
    if (!foundGroupe){
        throw new Error('Groupe non trouvé !');
    }
    return foundGroupe;
}


}