import { Injectable } from "@angular/core";
import { Personnage } from "../models/Personnage";
import { GroupeMock } from "../models/groupeMock";
import { PersonnageShort } from "../models/PersonnageShort";

@Injectable({ providedIn: 'root' })
export class MockGroupeService {

    groupeList: GroupeMock[] = [
        new GroupeMock(1, "L’équipage du Chapeau de Paille",
            [new PersonnageShort(1, "Monkey D Luffy"),
            new PersonnageShort(2, "Roronoa Zoro"),
            new PersonnageShort(3, "Nami"),
            new PersonnageShort(4, "Usopp"),
            new PersonnageShort(5, "Sanji"),
            new PersonnageShort(6, "Tony-Tony Chopper"),
            new PersonnageShort(7, "Nico Robin"),
            new PersonnageShort(8, "Franky"),
            new PersonnageShort(9, "Brook"),
            new PersonnageShort(10, "Jinbe"),
            new PersonnageShort(11, "Zeus"),
            new PersonnageShort(508, "Laboon"),
        ]).withCapitaine(new PersonnageShort(1, "Monkey D Luffy")),
        new GroupeMock(2, "L’équipage du Roux", [
            new PersonnageShort(85, "Shanks"),
            new PersonnageShort(86, "Ben Beckmann"),
            new PersonnageShort(87, "Lucky Roo"),
            new PersonnageShort(88, "Yassop"),
            new PersonnageShort(89, "Limejuice"),
            new PersonnageShort(90, "Bonk Punch"),
            new PersonnageShort(91, "Monster"),
            new PersonnageShort(92, "Building Snake"),
            new PersonnageShort(93, "Hongo"),
            new PersonnageShort(94, "Howling Dab"),
            new PersonnageShort(95, "Rockstar"),
        ]).withCapitaine(new PersonnageShort(85, "Shanks")),
        new GroupeMock(3, "L’équipage d’Alvida", [
            new PersonnageShort(33, "Alvida")
        ]).withCapitaine(new PersonnageShort(33, "Alvida")),
        new GroupeMock(4, "L’équipage du Clown", [
            new PersonnageShort(32, "Baggy / Le Clown")
        ]).withCapitaine(new PersonnageShort(32, "Baggy / Le Clown")),
        new GroupeMock(5, "L’équipage des Pirates Roger",
            [new PersonnageShort(258, "Gol D. Roger"),
            new PersonnageShort(259, "Silvers Rayleigh"),
            new PersonnageShort(260, "Scopper Gaban"),
            new PersonnageShort(261, "Seagull Guns Nozdon"),
            new PersonnageShort(262, "Taro"),
            new PersonnageShort(263, "Dringo"),
            new PersonnageShort(264, "Sanjuan Wolf"),
            new PersonnageShort(265, "Millet Pine"),
            new PersonnageShort(266, "Ganryu"),
            new PersonnageShort(267, "CB Galant"), 
            new PersonnageShort(268, "Donquino"), 
            new PersonnageShort(269, "Mr Momora"), 
            new PersonnageShort(270, "Moon Isaac Jr."), 
            new PersonnageShort(271, "Yui"), 
            new PersonnageShort(272, "Rangram"),
            new PersonnageShort(273, "Colonel Mugren"), 
            new PersonnageShort(274, "Max Marks"),
             new PersonnageShort(275, "Spencer"), 
             new PersonnageShort(276, "Bankro"),
              new PersonnageShort(277, "Blumarine"), 
              new PersonnageShort(278, "Elio"), 
              new PersonnageShort(279, "Rowing"), 
              new PersonnageShort(280, "Jacsonbaner"), 
              new PersonnageShort(281, "Yamon"),
            ]).withCapitaine(new PersonnageShort(258, "Gol D. Roger")),
        new GroupeMock(6, "L’équipage du Capitaine Usopp", [
            new PersonnageShort(4, "Usopp")
        ]).withCapitaine(new PersonnageShort(4, "Usopp")),
        new GroupeMock(7, "L’équipage du Chat Noir", [
            new PersonnageShort(37, "Kuro"), 
            new PersonnageShort(38, "Sham"), 
            new PersonnageShort(39, "Buchi"),
        ]).withCapitaine(new PersonnageShort(37, "Kuro")),
        new GroupeMock(8, "L’armada Pirate de Don Krieg", [
            new PersonnageShort(40, "Krieg / Don Krieg"), 
            new PersonnageShort(41, "Gyn"), 
            new PersonnageShort(42, "Pearl"),
        ]).withCapitaine(new PersonnageShort(40, "Krieg / Don Krieg")),
        new GroupeMock(9, "L’équipage des Cuisiniers", []),
        new GroupeMock(10, "L’équipage d’Arlong", [
            new PersonnageShort(282, "Arlong"), 
            new PersonnageShort(283, "Kuroobi"), 
            new PersonnageShort(284, "Smack"),
        ]).withCapitaine(new PersonnageShort(282, "Arlong")),
        new GroupeMock(11, "L’équipage des Pirates Yes", []),
        new GroupeMock(12, "L’équipage du Rumbar", [
            new PersonnageShort(285, "Yorki"), 
            new PersonnageShort(286, "Madaisky Mizuta"), 
            new PersonnageShort(287, "Mawaritovsky Mizuta"),
        ]).withCapitaine(new PersonnageShort(285, "Yorki")),
        new GroupeMock(13, "L’équipage des Géants", []),
        new GroupeMock(14, "L’équipage du Bliking", []),
        new GroupeMock(15, "L’équipage des Tulipes", []),
        new GroupeMock(16, "L’équipage de Barbe Blanche", [
            new PersonnageShort(289, "Edward Newgate / Barbe Blanche"), 
            new PersonnageShort(290, "Portgas D. Ace"), 
            new PersonnageShort(291, "Diamond Joz"), 
            new PersonnageShort(292, "Thatch"), 
            new PersonnageShort(293, "Vista"), 
            new PersonnageShort(294, "Blamenco"), 
            new PersonnageShort(295, "Rakuyo"), 
            new PersonnageShort(296, "Blenheim"), 
            new PersonnageShort(297, "Curiel"), 
            new PersonnageShort(298, "Kingdew"), 
            new PersonnageShort(299, "Haruta"), 
            new PersonnageShort(300, "Atmos"), 
            new PersonnageShort(301, "Speed Jill"), 
            new PersonnageShort(302, "Fossa"), 
            new PersonnageShort(303, "Izou"), 
            new PersonnageShort(304, "Doma"), 
            new PersonnageShort(305, "Frères DeCalvan"), 
            new PersonnageShort(306, "Squardo"), 
            new PersonnageShort(307, "Whitey Bay"), 
            new PersonnageShort(308, "Little Oz Junior"), 
            new PersonnageShort(309, "Mc Guy"), 
            new PersonnageShort(310, "A.O"), 
            new PersonnageShort(311, "Karma"), 
            new PersonnageShort(312, "Elmy"), 
            new PersonnageShort(313, "Ramba"), 
            new PersonnageShort(314, "Delacuaji"), 
            new PersonnageShort(315, "Zodia"), 
            new PersonnageShort(316, "Palms"), 
            new PersonnageShort(317, "Bizarre"), 
            new PersonnageShort(318, "Pavlik"), 
            new PersonnageShort(319, "Vitan"), 
            new PersonnageShort(320, "Islewan"), 
            new PersonnageShort(321, "Epoida"), 
            new PersonnageShort(322, "Kechatch"), 
            new PersonnageShort(323, "Choi"), 
            new PersonnageShort(324, "Arhur"), 
            new PersonnageShort(325, "Hangan"), 
            new PersonnageShort(326, "Reforte"), 
            new PersonnageShort(327, "Andre"), 
            new PersonnageShort(328, "Ninth"), 
            new PersonnageShort(329, "Blondie"), 
            new PersonnageShort(330, "Nosgarl"), 
            new PersonnageShort(331, "Amadob"), 
            new PersonnageShort(332, "Baggaley"), 
            new PersonnageShort(333, "Wakkem"), 
            new PersonnageShort(334, "Brew"), 
            new PersonnageShort(335, "Brocca"), 
            new PersonnageShort(336, "Rush"), 
            new PersonnageShort(337, "Great Micheal"), 
            new PersonnageShort(338, "Zucca"), 
            new PersonnageShort(339, "Cands"), 
            new PersonnageShort(340, "Kinga"), 
            new PersonnageShort(341, "Colscon"), 
            new PersonnageShort(342, "Agsilly"), 
            new PersonnageShort(343, "Julius"), 
            new PersonnageShort(344, "Happygun"), 
            new PersonnageShort(345, "Sleepy"),
             new PersonnageShort(346, "Forliewbs"),
            ]).withCapitaine(new PersonnageShort(289, "Edward Newgate / Barbe Blanche")),
        new GroupeMock(17, "Ligue des Primates", [
            new PersonnageShort(43, "Montblanc Cricket"), 
            new PersonnageShort(44, "Masira"), 
            new PersonnageShort(45, "Shojo"),
        ]).withCapitaine(new PersonnageShort(43, "Montblanc Cricket")),
        new GroupeMock(18, "L’équipage de Hakahoka", []),
        new GroupeMock(19, "l’équipage du New Age", []),
        new GroupeMock(20, "L’équipage de Roshio", []),
        new GroupeMock(21, "L’équipage de Don Quichotte", [
            new PersonnageShort(365, "Don Quijote Doflamingo"), 
            new PersonnageShort(366, "Trébol"), 
            new PersonnageShort(367, "Diamante"), 
            new PersonnageShort(368, "Pica"), 
            new PersonnageShort(369, "Vergo"), 
            new PersonnageShort(370, "Sugar"), 
            new PersonnageShort(371, "Jora"), 
            new PersonnageShort(372, "Lao G"), 
            new PersonnageShort(373, "Señor Pink"), 
            new PersonnageShort(374, "Machvise"), 
            new PersonnageShort(375, "Dellinger"), 
            new PersonnageShort(376, "Gladius"), 
            new PersonnageShort(377, "Buffallo"), 
            new PersonnageShort(378, "Monet"),
            new PersonnageShort(689, "Bellamy"),
        ]).withCapitaine(new PersonnageShort(365, "Don Quijote Doflamingo")),
        new GroupeMock(22, "L’équipage de Barbe Noire", [
            new PersonnageShort(247, "Marchall D. Teach / Barbe Noire"), 
            new PersonnageShort(248, "Jesus Burgess"), 
            new PersonnageShort(249, "Shiliew"), 
            new PersonnageShort(250, "Van Auger"), 
            new PersonnageShort(251, "Avalo Pizarro"), 
            new PersonnageShort(252, "Lafitte"), 
            new PersonnageShort(253, "Catarina Devon"), 
            new PersonnageShort(254, "Sanjuan Wolf"), 
            new PersonnageShort(255, "Vasco Shot"), 
            new PersonnageShort(256, "Doc Q"), 
            new PersonnageShort(257, "Barbe Rose"), 
            new PersonnageShort(762, "Stronger"),
        ]).withCapitaine(new PersonnageShort(247, "Marchall D. Teach / Barbe Noire")),
        new GroupeMock(23, "L’équipage des Fanged Toad", []),
        new GroupeMock(24, "L’équipage de Foxy", [
            new PersonnageShort(46, "Foxy"), 
            new PersonnageShort(47, "Porché"), 
            new PersonnageShort(48, "Hamburg"),
        ]).withCapitaine(new PersonnageShort(46, "Foxy")),
        new GroupeMock(25, "L’équipage des Gros Casques", []),
        new GroupeMock(26, "L’équipage des Pirates du Soleil", [
            new PersonnageShort(78, "Ficher Tiger"), 
            new PersonnageShort(79, "Aladdin"), 
            new PersonnageShort(80, "Charlotte Praliné"),
        ]).withCapitaine(new PersonnageShort(78, "Ficher Tiger")),
        new GroupeMock(27, "Pirate de l’Espace", []),
        new GroupeMock(28, "Thriller Bark", [
            new PersonnageShort(49, "Gecko Moria"), 
            new PersonnageShort(50, "Hogback"), 
            new PersonnageShort(51, "Absalom"), 
            new PersonnageShort(52, "Perona"),
        ]).withCapitaine(new PersonnageShort(49, "Gecko Moria")),
        new GroupeMock(29, "L’équipage du Rolling", [
            new PersonnageShort(53, "Laura"),
        ]).withCapitaine(new PersonnageShort(53, "Laura")),
        new GroupeMock(30, "L’équipage des Marquereaux", []),
        new GroupeMock(31, "L’équipage des Candys", []),
        new GroupeMock(32, "L’équipage du Hearth", [
            new PersonnageShort(54, "Trafalgar D. Water Law"), 
            new PersonnageShort(55, "Bepo"), 
            new PersonnageShort(56, "Jean Bart"), 
            new PersonnageShort(57, "Shachi"), 
            new PersonnageShort(58, "Pingouin"),
        ]).withCapitaine(new PersonnageShort(54, "Trafalgar D. Water Law")),
        new GroupeMock(33, "L’équipage de Kid", [
            new PersonnageShort(59, "Eustass Kidd"), 
            new PersonnageShort(60, "Killer"), 
            new PersonnageShort(61, "Heat"), 
            new PersonnageShort(62, "Wire"),
        ]).withCapitaine(new PersonnageShort(59, "Eustass Kidd")),
        new GroupeMock(34, "L’équipage de Hawkins", []),
        new GroupeMock(35, "L’équipage de Drake", []),
        new GroupeMock(36, "L’équipage du On-Air", []),
        new GroupeMock(37, "L’équipage de Bonney", []),
        new GroupeMock(38, "L’équipage du Fire Tank", [
            new PersonnageShort(63, "Capone Bege"), 
            new PersonnageShort(64, "Vito"), 
            new PersonnageShort(65, "Gotti"), 
            new PersonnageShort(66, "Charlotte Chiffon"), 
            new PersonnageShort(67, "Charlotte Pets"), 
            new PersonnageShort(68, "Jewelry Bonney"),
        ]).withCapitaine(new PersonnageShort(63, "Capone Bege")),
        new GroupeMock(39, "L’équipage des Moines Dépravés", [
            new PersonnageShort(69, "Urouge"),
        ]).withCapitaine(new PersonnageShort(69, "Urouge")),
        new GroupeMock(40, "L’équipage des Acumates", []),
        new GroupeMock(41, "L’équipage des Pirates Kuja", [
            new PersonnageShort(70, "Boa Hancock"), 
            new PersonnageShort(71, "Boa Sandersonia"), 
            new PersonnageShort(72, "Boa Marigold"), 
            new PersonnageShort(73, "Margaret"),
        ]).withCapitaine(new PersonnageShort(70, "Boa Hancock")),
        new GroupeMock(42, "L’équipage des Spade", []),
        new GroupeMock(43, "L’équipage de Barbe Brune", [
            new PersonnageShort(347, "Barbos Bruneriguez / Barbe Brune"),]
        ).withCapitaine(new PersonnageShort(347, "Barbos Bruneriguez / Barbe Brune")),
        new GroupeMock(44, "L’équipage aux Cent Bêtes", [
            new PersonnageShort(187, "Kaido"), 
            new PersonnageShort(188, "King"), 
            new PersonnageShort(189, "Queen"), 
            new PersonnageShort(190, "Jack"), 
            new PersonnageShort(191, "Page One"), 
            new PersonnageShort(192, "Ulti"), 
            new PersonnageShort(193, "Who’s Who"), 
            new PersonnageShort(194, "Black Maria"), 
            new PersonnageShort(195, "Sasaki"), 
            new PersonnageShort(196, "Sheep’s Head"), 
            new PersonnageShort(197, "Basil Hawkins"), 
            new PersonnageShort(198, "Holdem"), 
            new PersonnageShort(199, "Speed"), 
            new PersonnageShort(200, "Trouduc"), 
            new PersonnageShort(201, "Pouilleux"), 
            new PersonnageShort(202, "Solitaire"), 
            new PersonnageShort(203, "Bao Huang"), 
            new PersonnageShort(204, "Ginrummy"), 
            new PersonnageShort(205, "Plouf"), 
            new PersonnageShort(206, "Briscola"), 
            new PersonnageShort(207, "Fourtricks"), 
            new PersonnageShort(208, "Hamlet"), 
            new PersonnageShort(209, "Mizerka"), 
            new PersonnageShort(210, "Poker"), 
            new PersonnageShort(211, "Batman"), 
            new PersonnageShort(212, "Gazelleman"), 
            new PersonnageShort(213, "Mouseman"), 
            new PersonnageShort(214, "Snakeman"), 
            new PersonnageShort(215, "Rabitman"), 
            new PersonnageShort(216, "Sarehebi"), 
            new PersonnageShort(217, "Alpagaman"), 
            new PersonnageShort(218, "Tatouman"), 
            new PersonnageShort(219, "Dachoman"), 
            new PersonnageShort(220, "Tenjo-Sagari"), 
            new PersonnageShort(221, "Caimanlady"), 
            new PersonnageShort(222, "Nuré-Onna"), 
            new PersonnageShort(223, "Wa-Nyudo"), 
            new PersonnageShort(224, "Inbi"), 
            new PersonnageShort(225, "Fuga"), 
            new PersonnageShort(226, "Zanki"), 
            new PersonnageShort(227, "Jaki"), 
            new PersonnageShort(228, "Goki"), 
            new PersonnageShort(229, "Rokki"), 
            new PersonnageShort(230, "Nangi"), 
            new PersonnageShort(231, "Hacha"), 
            new PersonnageShort(232, "Kunyun"), 
            new PersonnageShort(233, "Juki"), 
            new PersonnageShort(234, "Fukurokuju"), 
            new PersonnageShort(235, "Daikoku"), 
            new PersonnageShort(236, "Hanzo"), 
            new PersonnageShort(237, "Sarutobi"), 
            new PersonnageShort(238, "Kazekage"), 
            new PersonnageShort(239, "Jigoku Benten"), 
            new PersonnageShort(240, "Fujin"), 
            new PersonnageShort(241, "Raijin"), 
            new PersonnageShort(242, "Bishamon"), 
            new PersonnageShort(243, "Tohomé"), 
            new PersonnageShort(244, "Yazaémon"), 
            new PersonnageShort(245, "Hotei"), 
            new PersonnageShort(246, "Scratchmen Apoo"),
        ]).withCapitaine(new PersonnageShort(187, "Kaido")),
        new GroupeMock(45, "L’équipage du Lion d’Or", [
            new PersonnageShort(74, "Shiki"), 
            new PersonnageShort(75, "Indigo"), 
            new PersonnageShort(730, "Scarlett"), 
            new PersonnageShort(731, "Billy"), 
            new PersonnageShort(732, "Xiao"),
        ]).withCapitaine(new PersonnageShort(74, "Shiki")),
        new GroupeMock(46, "L’équipage du Bluejam", [
            new PersonnageShort(348, "Bluejam"), 
            new PersonnageShort(349, "Porchemy"),
        ]).withCapitaine(new PersonnageShort(348, "Bluejam")),
        new GroupeMock(47, "L’équipage ASL", []),
        new GroupeMock(48, "Faux Equipage du Chapeau de Paille", [
            new PersonnageShort(350, "Demaro Black"), 
            new PersonnageShort(351, "Manjaro"), 
            new PersonnageShort(352, "Chocolat"), 
            new PersonnageShort(353, "Mounblutain"), 
            new PersonnageShort(354, "Drip"), 
            new PersonnageShort(355, "Nora Gitsune"), 
            new PersonnageShort(356, "Cocoa"), 
            new PersonnageShort(357, "Turco"),
        ]).withCapitaine(new PersonnageShort(350, "Demaro Black")),
        new GroupeMock(49, "L’équipage de Caribou", [
            new PersonnageShort(76, "Caribou"), 
            new PersonnageShort(77, "Coribou"),
        ]).withCapitaine(new PersonnageShort(76, "Caribou")),
        new GroupeMock(50, "L’équipage des Nouveaux Hommes-Poissons", [
            new PersonnageShort(358, "Hody Jones"), 
            new PersonnageShort(359, "Dosun"), 
            new PersonnageShort(360, "Zeo"), 
            new PersonnageShort(361, "Daruma"), 
            new PersonnageShort(362, "Ikaros Much"), 
            new PersonnageShort(363, "Hyozo"),
        ]).withCapitaine(new PersonnageShort(358, "Hody Jones")),
        new GroupeMock(51, "L’équipage des Pirates Volants", [
            new PersonnageShort(364, "Vander Decken IX"),
        ]).withCapitaine(new PersonnageShort(364, "Vander Decken IX")),
        new GroupeMock(52, "L’équipage de Gyro", []),
        new GroupeMock(53, "L’équipage de Big Mom", [
            new PersonnageShort(96, "Charlotte Linlin / Big Mom"), 
            new PersonnageShort(97, "Charlotte Dent-de-chien"), 
            new PersonnageShort(98, "Charlotte Smoothie"), 
            new PersonnageShort(99, "Charlotte Cracker"), 
            new PersonnageShort(100, "Charlotte Slurp"), 
            new PersonnageShort(101, "Charlotte Daifuku"), 
            new PersonnageShort(102, "Charlotte Oven"), 
            new PersonnageShort(103, "Charlotte Amande"), 
            new PersonnageShort(104, "Charlotte Opéra"), 
            new PersonnageShort(105, "Charlotte Brûlée"), 
            new PersonnageShort(106, "Charlotte Mont d’Or"), 
            new PersonnageShort(107, "Charlotte Galette"), 
            new PersonnageShort(108, "Charlotte Snack"), 
            new PersonnageShort(109, "Charlotte Pudding"), 
            new PersonnageShort(110, "Charlotte Flampée"), 
            new PersonnageShort(111, "Charlotte Compote"), 
            new PersonnageShort(112, "Charlotte Mondé"), 
            new PersonnageShort(113, "Charlotte Hachée"), 
            new PersonnageShort(114, "Charlotte Effilée"), 
            new PersonnageShort(115, "Charlotte Counter"), 
            new PersonnageShort(116, "Charlotte Cadenza"), 
            new PersonnageShort(117, "Charlotte Cabaletta"), 
            new PersonnageShort(118, "Charlotte Gala"), 
            new PersonnageShort(119, "Charlotte Angel"), 
            new PersonnageShort(120, "Charlotte Crème"), 
            new PersonnageShort(121, "Charlotte Zuccoto"), 
            new PersonnageShort(122, "Charlotte Broyée"), 
            new PersonnageShort(123, "Charlotte Nusstorte"), 
            new PersonnageShort(124, "Charlotte Basskarte"), 
            new PersonnageShort(125, "Charlotte Dosmarché"), 
            new PersonnageShort(126, "Charlotte Noisette"), 
            new PersonnageShort(127, "Charlotte Moscato"), 
            new PersonnageShort(128, "Charlotte Mash"), 
            new PersonnageShort(129, "Charlotte Corn Starch"), 
            new PersonnageShort(130, "Charlotte Compo"), 
            new PersonnageShort(131, "Charlotte Laurin"), 
            new PersonnageShort(132, "Charlotte Mozart"), 
            new PersonnageShort(133, "Charlotte Marnier"), 
            new PersonnageShort(134, "Charlotte High-Fat"), 
            new PersonnageShort(135, "Charlotte Tablet"), 
            new PersonnageShort(136, "Charlotte Citron"), 
            new PersonnageShort(137, "Charlotte Cannelle"), 
            new PersonnageShort(138, "Charlotte Saint-Marc"), 
            new PersonnageShort(139, "Charlotte Basans"), 
            new PersonnageShort(140, "Charlotte Mélisée"), 
            new PersonnageShort(141, "Charlotte Dacquoise"), 
            new PersonnageShort(142, "Charlotte Poire"), 
            new PersonnageShort(143, "Charlotte Bavarois"), 
            new PersonnageShort(144, "Charlotte Prim"), 
            new PersonnageShort(145, "Charlotte Kanten"), 
            new PersonnageShort(146, "Charlotte Kato"), 
            new PersonnageShort(147, "Charlotte Montb"), 
            new PersonnageShort(148, "Charlotte Chiboust"), 
            new PersonnageShort(149, "Charlotte Mobile"), 
            new PersonnageShort(150, "Charlotte Marble"), 
            new PersonnageShort(151, "Charlotte Mucre"), 
            new PersonnageShort(152, "Charlotte Mapple"), 
            new PersonnageShort(153, "Charlotte Brownie"), 
            new PersonnageShort(154, "Charlotte Joconde"), 
            new PersonnageShort(155, "Charlotte Raisin"), 
            new PersonnageShort(156, "Charlotte Panna"), 
            new PersonnageShort(157, "Charlotte Mascarpone"), 
            new PersonnageShort(158, "Charlotte Joscarpone"), 
            new PersonnageShort(159, "Charlotte Yu Yuan"), 
            new PersonnageShort(160, "Charlotte Newichi"), 
            new PersonnageShort(161, "Charlotte Newji"), 
            new PersonnageShort(162, "Charlotte Newsan"), 
            new PersonnageShort(163, "Charlotte Newshi"), 
            new PersonnageShort(164, "Charlotte Newgo"), 
            new PersonnageShort(165, "Charlotte Muscade"), 
            new PersonnageShort(166, "Charlotte Muscadia"), 
            new PersonnageShort(167, "Charlotte Muscadelle"), 
            new PersonnageShort(168, "Charlotte Muscadine"), 
            new PersonnageShort(169, "Charlotte Muscadette"), 
            new PersonnageShort(170, "Charlotte Nougat"), 
            new PersonnageShort(171, "Charlotte Anglais"), 
            new PersonnageShort(172, "Charlotte Wafers"), 
            new PersonnageShort(173, "Charlotte Wiro"), 
            new PersonnageShort(174, "Charlotte De-Chat"), 
            new PersonnageShort(175, "Charlotte Normande"), 
            new PersonnageShort(176, "Charlotte Dolce"), 
            new PersonnageShort(177, "Charlotte Dragée"), 
            new PersonnageShort(178, "Charlotte Anana"), 
            new PersonnageShort(179, "Pekoms"), 
            new PersonnageShort(180, "Delœuf"), 
            new PersonnageShort(181, "Boddin"), 
            new PersonnageShort(182, "Streusen"), 
            new PersonnageShort(183, "Prométhée"), 
            new PersonnageShort(184, "Napoléon"), 
            new PersonnageShort(185, "Héra"), 
            new PersonnageShort(186, "Kingbaum"),
        ]).withCapitaine(new PersonnageShort(96, "Charlotte Linlin / Big Mom")),
        new GroupeMock(54, "L’équipage d’Expédition", []),
        new GroupeMock(55, "L’équipage des Magnifiques Pirates", []),
        new GroupeMock(56, "L’équipage de Bartolomeo", [
            new PersonnageShort(14, "Bartolomeo")
        ]).withCapitaine(new PersonnageShort(14, "Bartolomeo")),
        new GroupeMock(57, "Flotte Yonta Maria", [
            new PersonnageShort(754, "Orlombus"),
        ]).withCapitaine(new PersonnageShort(754, "Orlombus")),
        new GroupeMock(58, "L’équipage du Croissant de Lune", []),
        new GroupeMock(59, "L’équipage de Diez Barrels", []),
        new GroupeMock(60, "XXX Gym Martial Arts Alliances", []),
        new GroupeMock(61, "Nouvel Equipage des Géants", []),
        new GroupeMock(62, "L’équipage de Rocks", [
            new PersonnageShort(379, "Rocks D. Xebec"),
            new PersonnageShort(96, "Charlotte Linlin / Big Mom"),
            new PersonnageShort(74, "Shiki"),
            new PersonnageShort(187, "Kaido"),
            new PersonnageShort(289, "Edward Newgate / Barbe Blanche"), 
            ]).withCapitaine(new PersonnageShort(379, "Rocks D. Xebec")),
        new GroupeMock(63, "l’équipage de Ganzack", []),
        new GroupeMock(64, "L’équipage Amigo", []),
        new GroupeMock(65, "L’équipage du Phoenix", []),
        new GroupeMock(66, "L’équipage de Bayan", []),
        new GroupeMock(67, "L’équipage des Pirates Schneider", [
            new PersonnageShort(733, "Schneider"), 
            new PersonnageShort(734, "Buzz"),
        ]).withCapitaine(new PersonnageShort(733, "Schneider")),
        new GroupeMock(68, "L’équipage de Wetton", []),
        new GroupeMock(69, "Les Pirates à la citrouille", []),
        new GroupeMock(70, "L’équipage des Flèches Rouges", []),
        new GroupeMock(71, "L’équipage des Pirates à la Moustache", []),
        new GroupeMock(72, "L’équipage des Pirates Trump", [
            new PersonnageShort(698, "Bear King"), 
            new PersonnageShort(699, "Honey Queen"), 
            new PersonnageShort(700, "Pin Joker"), 
            new PersonnageShort(701, "Boo Jack"), 
            new PersonnageShort(702, "Skunk One"),
        ]).withCapitaine(new PersonnageShort(698, "Bear King")),
        new GroupeMock(73, "L’équipage de Gasparde", [
            new PersonnageShort(709, "Général Gasparde"), 
            new PersonnageShort(710, "Needless"), 
            new PersonnageShort(711, "Biera"), 
            new PersonnageShort(712, "Shuraiya Bascùd"), 
            new PersonnageShort(713, "Adelle Bascùd"),
        ]).withCapitaine(new PersonnageShort(709, "Général Gasparde")),
        new GroupeMock(74, "L’équipage de Zenny", []),
        new GroupeMock(75, "L’équipage des Pirates du Sables", []),
        new GroupeMock(76, "L’équipage Tearoom", []),
        new GroupeMock(77, "L’équipage des Pirates Treasure", []),
        new GroupeMock(78, "Baroque Works", []),
        new GroupeMock(79, "Royaume de Luvneel", []),
        new GroupeMock(80, "La Flotte de Happou", []),
        new GroupeMock(81, "L'Équipage des Maquereaux", [new PersonnageShort(755, "Macro"),]),
        new GroupeMock(82, "Marine", [
            new PersonnageShort(414, "Sakazuki / Akainu"), 
            new PersonnageShort(415, "Borsalino / Kizaru"), 
            new PersonnageShort(416, "Issho / Fujitora"), 
            new PersonnageShort(417, "Aramaki / Ryokugyu"), 
            new PersonnageShort(418, "Monkey D. Garp"), 
            new PersonnageShort(419, "Tsuru"), 
            new PersonnageShort(420, "John Giant"), 
            new PersonnageShort(421, "Comir"), 
            new PersonnageShort(422, "Momonga"), 
            new PersonnageShort(423, "Onigumo"), 
            new PersonnageShort(424, "Doberman"), 
            new PersonnageShort(425, "Strawberry"), 
            new PersonnageShort(426, "Yamakaji"), 
            new PersonnageShort(427, "Dalmatien"), 
            new PersonnageShort(428, "Bastille"), 
            new PersonnageShort(429, "Smoker"), 
            new PersonnageShort(430, "Maynard"), 
            new PersonnageShort(431, "Tokikake"), 
            new PersonnageShort(432, "Hina"), 
            new PersonnageShort(433, "T. Bone"), 
            new PersonnageShort(434, "Pudding"), 
            new PersonnageShort(435, "Jenfétro"), 
            new PersonnageShort(436, "Brandnew"), 
            new PersonnageShort(437, "Verygood"), 
            new PersonnageShort(438, "Shu"), 
            new PersonnageShort(439, "Sharinguru"), 
            new PersonnageShort(440, "Tashigi"), 
            new PersonnageShort(441, "Kobby"), 
            new PersonnageShort(442, "Nezumi"), 
            new PersonnageShort(443, "Don Quijote Rosinante"), 
            new PersonnageShort(444, "Hermep"), 
            new PersonnageShort(445, "Fullbody"), 
            new PersonnageShort(446, "Jango"), 
            new PersonnageShort(447, "Sengoku"), 
            new PersonnageShort(448, "Sentomaru"), 
            new PersonnageShort(449, "X-Drake"), 
            new PersonnageShort(450, "Kaiser Moustache"), 
            new PersonnageShort(451, "Cancer"), 
            new PersonnageShort(452, "Mozambia"), 
            new PersonnageShort(453, "Lacroix"), 
            new PersonnageShort(454, "Ronz"), 
            new PersonnageShort(455, "Dohn Deynon"), 
            new PersonnageShort(456, "Draw"), 
            new PersonnageShort(457, "Sicily"), 
            new PersonnageShort(458, "Akehende"), 
            new PersonnageShort(459, "Catacombo"), 
            new PersonnageShort(460, "Kadar"), 
            new PersonnageShort(461, "Daigin"), 
            new PersonnageShort(462, "Gorilla"),
             new PersonnageShort(756, "Pudding Pudding"),
            ]).withCapitaine(new PersonnageShort(414, "Sakazuki / Akainu")),
        new GroupeMock(83, "Dragon Célestes", [
            new PersonnageShort(386, "Roswald"), 
            new PersonnageShort(387, "Charloss"), 
            new PersonnageShort(388, "Sharlia"), 
            new PersonnageShort(389, "Don Quijote Myosgard"), 
            new PersonnageShort(390, "Jalmack"), 
            new PersonnageShort(498, "Don Quijote Homing"),
        ]),
        new GroupeMock(84, "Bigaro", []),
        new GroupeMock(85, "L'Équipage de Mad Treasure", []),
        new GroupeMock(86, "Royaume de Tontatta", []),
        new GroupeMock(87, "Armada du Chapeau de Paille", [
            new PersonnageShort(12, "Cavendish"), 
            new PersonnageShort(13, "Suleiman"), 
            new PersonnageShort(14, "Bartolomeo"), 
            new PersonnageShort(15, "Gambia"), 
            new PersonnageShort(16, "Sai"), 
            new PersonnageShort(17, "Boo"), 
            new PersonnageShort(18, "Baby 5"), 
            new PersonnageShort(19, "Ideo"), 
            new PersonnageShort(20, "Blue Gilly"), 
            new PersonnageShort(21, "Abdullah"), 
            new PersonnageShort(22, "Jeet"), 
            new PersonnageShort(23, "Léo"), 
            new PersonnageShort(24, "Kabu"), 
            new PersonnageShort(25, "Bee Anne"), 
            new PersonnageShort(26, "Hajrudin"), 
            new PersonnageShort(27, "Stansen"), 
            new PersonnageShort(28, "Road"), 
            new PersonnageShort(29, "Goldberg"), 
            new PersonnageShort(30, "Gerd"), 
            new PersonnageShort(31, "Orlumbus"),
        ]),
        new GroupeMock(88, "Baggy's Delivery", [
            new PersonnageShort(32, "Baggy / Le Clown"), 
            new PersonnageShort(33, "Alvida"), 
            new PersonnageShort(34, "Galdino"), 
            new PersonnageShort(35, "Morge"), 
            new PersonnageShort(36, "Cabaji"),
        ]).withCapitaine(new PersonnageShort(32, "Baggy / Le Clown")),
        new GroupeMock(89, "Conseil des doyens", [
            new PersonnageShort(380, "Im Sama"), 
            new PersonnageShort(381, "1er Doyen"), 
            new PersonnageShort(382, "2e Doyen"), 
            new PersonnageShort(383, "3e Doyen"), 
            new PersonnageShort(384, "4e Doyen"), 
            new PersonnageShort(385, "5e Doyen"),
        ]),
        new GroupeMock(90, "Cipher Pol", [new PersonnageShort(391, "Guernica"), new PersonnageShort(392, "Rob Lucci"), new PersonnageShort(393, "Hittori"), new PersonnageShort(394, "Spandam"), new PersonnageShort(395, "Funckfreed"), new PersonnageShort(396, "Kaku"), new PersonnageShort(397, "Stussy"), new PersonnageShort(398, "Maha"), new PersonnageShort(399, "Jerry"), new PersonnageShort(400, "Wanzé"),]),
        new GroupeMock(91, "Enies Lobby", [new PersonnageShort(401, "Bas"), new PersonnageShort(402, "And"), new PersonnageShort(403, "Kerville"),]),
        new GroupeMock(92, "Impel Down", [new PersonnageShort(404, "Hannyabal"), new PersonnageShort(405, "Magellan"), new PersonnageShort(406, "Domino"), new PersonnageShort(407, "Saldeath"), new PersonnageShort(408, "Sadi"), new PersonnageShort(409, "Minotaure"), new PersonnageShort(410, "Minokoala"), new PersonnageShort(411, "Minorhinocéros"), new PersonnageShort(412, "Minozèbre"), new PersonnageShort(413, "Minochihuabua"),]),
        new GroupeMock(93, "Royaume de Goa", [new PersonnageShort(463, "Stelly"), new PersonnageShort(464, "Sally Entoilette"), new PersonnageShort(465, "Outlook III"), new PersonnageShort(466, "Didit"), new PersonnageShort(467, "Makino"), new PersonnageShort(468, "Woop Slap"), new PersonnageShort(469, "Curly Dadan"), new PersonnageShort(470, "Dogra"), new PersonnageShort(471, "Magra"), new PersonnageShort(472, "Higuma"),]),
        new GroupeMock(94, "Village de Shimotsuki", [new PersonnageShort(473, "Kozaburo Shimotsuki"), new PersonnageShort(474, "Koshiro"), new PersonnageShort(475, "Kuina"),]),
        new GroupeMock(95, "Archipel des Argao", [new PersonnageShort(476, "Boodle"), new PersonnageShort(477, "Chouchou"),]),
        new GroupeMock(96, "Île des animaux étranges", [new PersonnageShort(478, "Gaimone"), new PersonnageShort(479, "Sarfunkel"),]),
        new GroupeMock(97, "Archipel des Gecko", [new PersonnageShort(480, "Kaya"), new PersonnageShort(481, "Merry"), new PersonnageShort(482, "Oignon"), new PersonnageShort(483, "Piment"), new PersonnageShort(484, "Carotte"), new PersonnageShort(485, "Banchina"),]),
        new GroupeMock(98, "Baratie", [new PersonnageShort(486, "Zeff"), new PersonnageShort(487, "Patty"), new PersonnageShort(488, "Canne"),]),
        new GroupeMock(99, "Archipel Conomi", [new PersonnageShort(489, "Belmer"), new PersonnageShort(490, "Nojiko"), new PersonnageShort(491, "Genzo"), new PersonnageShort(492, "Nako"), new PersonnageShort(493, "Chabo"), new PersonnageShort(494, "Johny"), new PersonnageShort(495, "Yosaku"),]),
        new GroupeMock(100, "Loguetown", [new PersonnageShort(496, "Ipponmatsu"),]),
        new GroupeMock(101, "Royaume de Lvneel", [new PersonnageShort(497, "Montblanc Norland"),]),
        new GroupeMock(102, "Baterilla", [new PersonnageShort(499, "Portgas D. Rouge"),]),
        new GroupeMock(103, "Royaume maléfique de Black Drum", [
            new PersonnageShort(500, "Wapol"), 
            new PersonnageShort(501, "Kinderella"), 
            new PersonnageShort(729, "Musshul"),
        ]).withCapitaine(new PersonnageShort(500, "Wapol")),
        new GroupeMock(104, "Ohara", [
            new PersonnageShort(502, "Clover"), 
            new PersonnageShort(503, "Nico Olvia"), 
            new PersonnageShort(504, "Haguar D. Sauro"),
            new PersonnageShort(7, "Nico Robin"),
        ]).withCapitaine(new PersonnageShort(502, "Clover")),
        new GroupeMock(105, "Pays des fleurs", [new PersonnageShort(505, "Ramen"), new PersonnageShort(506, "Chinjao"),]),
        new GroupeMock(106, "Reverse Mountain", []),
        new GroupeMock(107, "Île aux cactus", [new PersonnageShort(509, "Miss Monday"), new PersonnageShort(510, "Mr 9"),]),
        new GroupeMock(108, "Little Garden", [new PersonnageShort(511, "Dorry"), new PersonnageShort(512, "Broggy"),]),
        new GroupeMock(109, "Île de Drum", [new PersonnageShort(513, "Dolton"), new PersonnageShort(514, "Kureha"), new PersonnageShort(515, "Hiluluk"), new PersonnageShort(516, "Chess"), new PersonnageShort(517, "Kuromarimo"),]),
        new GroupeMock(110, "Alabasta", [
            new PersonnageShort(518, "Nefertari Cobra"), 
            new PersonnageShort(519, "Nefertari Titi"), 
            new PersonnageShort(520, "Nefertari Vivi"), 
            new PersonnageShort(521, "Igaram"), 
            new PersonnageShort(522, "Chaka"), 
            new PersonnageShort(523, "Pell"), 
            new PersonnageShort(524, "Kaloo"), 
            new PersonnageShort(525, "Longs-Cils"), 
            new PersonnageShort(526, "Stomp"), 
            new PersonnageShort(527, "Ivan X"), 
            new PersonnageShort(528, "Cowboy"), 
            new PersonnageShort(529, "Bourdon Jr."), 
            new PersonnageShort(530, "Kentarôs"), 
            new PersonnageShort(531, "Hikoichi"), 
            new PersonnageShort(532, "Koza"), 
            new PersonnageShort(533, "Toto"),
        ]).withCapitaine(new PersonnageShort(518, "Nefertari Cobra")),
        new GroupeMock(111, "Long Ring Long Land", [new PersonnageShort(534, "Tonjit"), new PersonnageShort(535, "Shelly"),]),
        new GroupeMock(112, "Source de l'insouciance", [new PersonnageShort(536, "Gedatsu"),]),
        new GroupeMock(113, "Water Seven", [
            new PersonnageShort(537, "Icebarg"), 
            new PersonnageShort(538, "Pauly"), 
            new PersonnageShort(539, "Peeply Lulu"), 
            new PersonnageShort(540, "Tilestone"), 
            new PersonnageShort(541, "Zanbai"), 
            new PersonnageShort(542, "Mozu"), 
            new PersonnageShort(543, "Kiwi"), 
            new PersonnageShort(544, "Tom"), 
            new PersonnageShort(545, "Kokoro"), 
            new PersonnageShort(546, "Chimney"), 
            new PersonnageShort(547, "Gonbei"), 
            new PersonnageShort(548, "Yokozuma"),
        ]).withCapitaine(new PersonnageShort(537, "Icebarg")),
        new GroupeMock(114, "Archipel des Sabaody", [new PersonnageShort(549, "Silvers Rayleigh"), new PersonnageShort(550, "Shakuyaku"), new PersonnageShort(551, "Disco"), new PersonnageShort(552, "Duval"),]),
        new GroupeMock(115, "Archipel de Boing", [new PersonnageShort(553, "Héraclès"),]),
        new GroupeMock(116, "Erbaf", [new PersonnageShort(554, "Loki"), new PersonnageShort(555, "Jorl"), new PersonnageShort(556, "Jarl"), new PersonnageShort(557, "Oimo"), new PersonnageShort(558, "Kaashii"),]),
        new GroupeMock(117, "Pays des Wa", [
            new PersonnageShort(559, "Sukiyaki Kozuki"), 
            new PersonnageShort(560, "Oden Kozuki"), 
            new PersonnageShort(561, "Toki Kozuki"), 
            new PersonnageShort(562, "Mononosuké Kozuki"), 
            new PersonnageShort(563, "Hiyori Kozuki"), 
            new PersonnageShort(564, "Kinémon"), 
            new PersonnageShort(565, "Denjiro"), 
            new PersonnageShort(566, "Izo"), 
            new PersonnageShort(567, "Kikunojo"), 
            new PersonnageShort(568, "Raizo"), 
            new PersonnageShort(569, "Ashura Doji"), 
            new PersonnageShort(570, "Kawamatsu"), 
            new PersonnageShort(571, "Shinobu"), 
            new PersonnageShort(572, "Orochi Kurozumi"), 
            new PersonnageShort(573, "Kanjuro Kurozumi"), 
            new PersonnageShort(574, "Semimaru Kurozumi"), 
            new PersonnageShort(575, "Higurashi Kurozumi"), 
            new PersonnageShort(576, "Ryuma Shimotsuki"), 
            new PersonnageShort(577, "Yasui Shimotsuki"), 
            new PersonnageShort(578, "Toko"), 
            new PersonnageShort(579, "Onimaru"), 
            new PersonnageShort(580, "Hyogoro"), 
            new PersonnageShort(581, "Omasa"), 
            new PersonnageShort(582, "Tsunagoro"), 
            new PersonnageShort(583, "Cho"), 
            new PersonnageShort(584, "Yatappé"), 
            new PersonnageShort(585, "Tama"), 
            new PersonnageShort(586, "Tsurujo"), 
            new PersonnageShort(587, "Komachiyo"), 
            new PersonnageShort(588, "Baboumaru"), 
            new PersonnageShort(589, "Bunbuku"), 
            new PersonnageShort(590, "Yamato"), 
            new PersonnageShort(749, "Tenguyama Hitetsu"),
        ]).withCapitaine(new PersonnageShort(562, "Mononosuké Kozuki")),
        new GroupeMock(118, "Punk Hazard", [new PersonnageShort(591, "Rock"), new PersonnageShort(592, "Scotch"), new PersonnageShort(593, "Smiley"), new PersonnageShort(691, "César Clown"),]),
        new GroupeMock(119, "Dressrosa", [
            new PersonnageShort(594, "Riku Dold III"), 
            new PersonnageShort(595, "Scarlett"), 
            new PersonnageShort(596, "Kyros"), 
            new PersonnageShort(597, "Viola"), 
            new PersonnageShort(598, "Rebecca"), 
            new PersonnageShort(599, "Gatz"), 
            new PersonnageShort(600, "Tank Lepanto"),
        ]).withCapitaine(new PersonnageShort(594, "Riku Dold III")),
        new GroupeMock(120, "Green Bit", [new PersonnageShort(601, "Guncho"), new PersonnageShort(602, "Manshelly"),]),
        new GroupeMock(121, "Zo", [new PersonnageShort(603, "Zunesh"), new PersonnageShort(604, "Bêgis Khan"), new PersonnageShort(605, "Caborage"), new PersonnageShort(606, "Chavipère"), new PersonnageShort(607, "Sicilion"), new PersonnageShort(608, "Cancelot"), new PersonnageShort(609, "Giovanni"), new PersonnageShort(610, "Wanda"), new PersonnageShort(611, "Carrot"), new PersonnageShort(612, "Pedro"),]),
        new GroupeMock(122, "Royaume de Prodence", [new PersonnageShort(613, "Elizabello II"), new PersonnageShort(614, "Dagama"),]),
        new GroupeMock(123, "Royaume de Mogalo", [new PersonnageShort(615, "Kelly Funk"), new PersonnageShort(616, "Bobby Funk"),]),
        new GroupeMock(124, "Royaume de Germa", [new PersonnageShort(617, "Judge Vinsmoke"), new PersonnageShort(618, "Sora Vinsmoke"), new PersonnageShort(619, "Reiju Vinsmoke"), new PersonnageShort(620, "Ichiji Vinsmoke"), new PersonnageShort(621, "Niji Vinsmoke"), new PersonnageShort(622, "Yonji Vinsmoke"),]),
        new GroupeMock(125, "Sphinx", [new PersonnageShort(623, "Marco"),]),
        new GroupeMock(126, "Skypiea", [new PersonnageShort(624, "Gan Forr"), new PersonnageShort(625, "Pierre"), new PersonnageShort(626, "Conis"), new PersonnageShort(627, "Pagaya"), new PersonnageShort(628, "Amazon"), new PersonnageShort(629, "Chef Shandia"), new PersonnageShort(630, "Wiper"), new PersonnageShort(631, "Kamakiri"), new PersonnageShort(632, "Braham"), new PersonnageShort(633, "Genbo"), new PersonnageShort(634, "Laki"), new PersonnageShort(635, "Aisa"), new PersonnageShort(636, "Nora"), new PersonnageShort(637, "Calgara"), new PersonnageShort(638, "Om"), new PersonnageShort(639, "Satori"), new PersonnageShort(640, "Shura"), new PersonnageShort(641, "Yama"), new PersonnageShort(642, "Hotori"), new PersonnageShort(643, "Kotori"),]),
        new GroupeMock(127, "Weatheria", [new PersonnageShort(644, "Haredas"),]),
        new GroupeMock(128, "Île des hommes-poissons", [new PersonnageShort(645, "Neptune"), new PersonnageShort(646, "Otohime"), new PersonnageShort(647, "Fukaboshi"), new PersonnageShort(648, "Ryuboshi"), new PersonnageShort(649, "Mamboshi"), new PersonnageShort(650, "Shirahoshi"), new PersonnageShort(651, "Hoé"), new PersonnageShort(652, "Mégalo"), new PersonnageShort(653, "Ministre Sénestre"), new PersonnageShort(654, "Ministre Dextre"), new PersonnageShort(655, "Shyarly"), new PersonnageShort(656, "Keimi"), new PersonnageShort(657, "Pappag"), new PersonnageShort(658, "Octy"), new PersonnageShort(659, "Den"),]),
        new GroupeMock(129, "La lune", [new PersonnageShort(660, "Ener"),]),
        new GroupeMock(130, "Armée Révolutionnaire", [
            new PersonnageShort(661, "Monkey D. Dragon"), 
            new PersonnageShort(662, "Sabo"), 
            new PersonnageShort(663, "Emporio Ivankov"), 
            new PersonnageShort(664, "Corbeau"), 
            new PersonnageShort(665, "Belo Betty"), 
            new PersonnageShort(666, "Morley"), 
            new PersonnageShort(667, "Lindbergh"), 
            new PersonnageShort(668, "Inazuma"), 
            new PersonnageShort(669, "Canard"), 
            new PersonnageShort(670, "Koala"), 
            new PersonnageShort(671, "Hack"), 
            new PersonnageShort(773, "Karazu"),
        ]).withCapitaine(new PersonnageShort(661, "Monkey D. Dragon")),
        new GroupeMock(131, "Anciens membres du Baroque Works", [new PersonnageShort(672, "Zala"), new PersonnageShort(673, "Bentham"), new PersonnageShort(674, "Marianne"), new PersonnageShort(675, "Babe"), new PersonnageShort(676, "Lassou"), new PersonnageShort(677, "Drophy"), new PersonnageShort(678, "Gemme"), new PersonnageShort(679, "Mikita"),]),
        new GroupeMock(132, "Anciens membres du Cipher Pol", [new PersonnageShort(680, "Jabura"), new PersonnageShort(681, "Blueno"), new PersonnageShort(682, "Kumadori"), new PersonnageShort(683, "Fukuro"), new PersonnageShort(684, "Kalifa"), new PersonnageShort(685, "Nero"), new PersonnageShort(686, "Spandine"),]),
        new GroupeMock(133, "Anciens membres de la Marine", [new PersonnageShort(687, "Kuzan / Aokiji"), new PersonnageShort(688, "Morgan"),]),
        new GroupeMock(134, "Esclave", [new PersonnageShort(690, "Bartholomew Kuma"),]),
        new GroupeMock(135, "Frères Voleurs", [new PersonnageShort(703, "Borodo"), new PersonnageShort(704, "Akisu"),]),
        new GroupeMock(136, "IÎle de la couronne", []),
        new GroupeMock(137, "Île d'Asuka", [new PersonnageShort(714, "Saga"), new PersonnageShort(715, "Toma"), new PersonnageShort(716, "Bismarck"), new PersonnageShort(717, "Boo Kong"), new PersonnageShort(718, "Maya"), new PersonnageShort(719, "Izaya"), new PersonnageShort(720, "Lacos"),]),
        new GroupeMock(138, "Pirate des flèches rouges", [new PersonnageShort(721, "Omatsuri"), new PersonnageShort(722, "Lily Carnation"),]),
        new GroupeMock(139, "Pirate au foyer", [new PersonnageShort(723, "Papa"),]),
        new GroupeMock(140, "Pirate Moustachus", [new PersonnageShort(724, "Brief"),]),
        new GroupeMock(141, "Île de Mecha", [new PersonnageShort(725, "Ratchet"), new PersonnageShort(726, "Honki"), new PersonnageShort(727, "Maji"), new PersonnageShort(728, "Roba"),]),
        new GroupeMock(142, "Néo Marine", [new PersonnageShort(735, "Zéphyr"), new PersonnageShort(736, "Ain"), new PersonnageShort(737, "Bins"),]),
        new GroupeMock(143, "Gran Tesero", [new PersonnageShort(738, "Gild Tesoro"), new PersonnageShort(739, "Baccarat"), new PersonnageShort(740, "Dice"), new PersonnageShort(741, "Tanaka"), new PersonnageShort(742, "Carina"),]),
        new GroupeMock(144, "Elegia", [new PersonnageShort(747, "Uta"), new PersonnageShort(748, "Gordon"),]),
        new GroupeMock(145, "World Economic Journal", [new PersonnageShort(692, "Morgans"),]),
        new GroupeMock(146, "Cap des Jumeaux", [new PersonnageShort(507, "Crocus"), new PersonnageShort(508, "Laboon"),]),
        new GroupeMock(147, "Equipage de Bellamy", [new PersonnageShort(288, "Sarquiss"),]),
        new GroupeMock(148, "Equipage de Pandaman", []),
        new GroupeMock(149, "Equipage de Bigalo", [new PersonnageShort(760, "Bigalo"),]),
    ];

    getGroupeList(): GroupeMock[] {
        return [...this.groupeList];
    }

    getGroupeById(groupeId: number): GroupeMock {
        const idNum = Number(groupeId);
        const foundGroupe = this.groupeList.find(Groupe => Groupe.id === idNum);
        if (!foundGroupe) {
            throw new Error('Groupe non trouvé !');
        }
        return foundGroupe;
    }

    getGroupeByName(nom: String): GroupeMock {
        const foundGroupe = this.groupeList.find(Groupe => Groupe.name === nom);
        if (!foundGroupe) {
            throw new Error('Groupe non trouvé !');
        }
        return foundGroupe;
    }


}