name: Build, Test & Deploy

on:
  push:
    branches: [master]

permissions:
  security-events: write
  contents: read

jobs:

  tests-deploiements: 
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '20'
          cache: 'npm'        
    - run: npm ci

    - name: CodeQL
      uses: github/codeql-action/init@v4
      with:
          languages: javascript-typescript

    - run: npm run build -- --configuration production
    - uses: github/codeql-action/analyze@v4 
    - run: npx ng serve --configuration production &
    - run: npx wait-on http://localhost:4200 --timeout 60000
    - run: npx cypress run --headless

    
  deploiement:
    runs-on: alpine-latest

    steps:
      - run: docker build -t one-piece-app .
      - run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

