name: Tests Integration

on:
  push:
    branches: [staging]

jobs:
  tests-integration:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 
      - run: npm ci

      - name: Tests unitaires 
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Build image Docker version staging
        run: docker build -t one-piece-staging .

      - name: Démarrer le conteneur staging
        run: |
          docker run -d \
            --name staging-app \
            -p 4200:80 \
            one-piece-staging
      - run: npx wait-on http://localhost:4200 --timeout 60000

      - name: Tests Cypress
        run: npx cypress run --headless
        env:
          CYPRESS_BASE_URL: http://localhost:4200

      - name: Arrêter le conteneur staging
        if: always() 
        run: |
          docker stop staging-app
          docker rm staging-app

      - name: Audit sécurité npm
        run: npm audit --audit-level=critical

      - name: Lint
        run: npx ng lint
      

              
