name: Test Integration

on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on : alpine-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installation des dépendances
        run: npm ci

      - name: Tests unitaires
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Tests Cypress
        run: npx cypress run --headless

      - name: Audit sécurité npm
        run: npm audit --audit-level=high

      - name: Lint
        run: npx ng lint
      

              
