name: Tests Integration

on:
  push:
    branches: [dev]

jobs:
  tests-integration:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' 
      - run: npm ci

      - name: Tests unitaires
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Tests Cypress
        run: npx ng serve --configuration production &
      - run: npx wait-on http://localhost:4200 --timeout 60000
      - run: npx cypress run --headless

      - name: Audit sécurité npm
        run: npm audit --audit-level=high

      - name: Lint
        run: npx ng lint
      

              
